temp = np.copy(smaller_maze)
print("BFS: ")
start = time.time()
trackBfs(temp, startXY)
end = time.time()
print("Time: "+str(round(end-start, 4)) + " seconds")
print("------------------------------------------------")
cv2.waitKey(0)

temp = np.copy(smaller_maze)
print("DFS: ")
start = time.time()
dfs(temp, startXY)
end = time.time()
print("Time: "+str(round(end-start, 4)) + " seconds")
print("------------------------------------------------")
cv2.waitKey(0)

temp = np.copy(smaller_maze)
print("Dijkstra: ")
start = time.time()
dijkstra(temp, startXY, endXY)
end = time.time()
print("Time: "+str(round(end-start, 4)) + " seconds")
print("------------------------------------------------")
cv2.waitKey(0)

temp = np.copy(smaller_maze)
print("A*: ")
start = time.time()
astar(temp, startXY, endXY)
end = time.time()
print("Time: "+str(round(end-start, 4)) + " seconds")
print("------------------------------------------------")
cv2.waitKey(0)

cv2.destroyAllWindows()